[package]
name = "syz"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "syzd"
path = "src/bin/syzd.rs"

[[bin]]
name = "syzctl"
path = "src/bin/syzctl.rs"

[dependencies]
tokio = { version = "1.50.0", features = ["full", "macros"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
tracing-journald = "0.3.2"
anyhow = "1.0.102"
turso = "0.7.0"
rand = "0.10.1"
bs58 = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde_yml = "0.0.12"
bytes = "1.11.1"
reqwest-middleware = "0.5.1"
reqwest-retry = "0.9.1"
reqwest-tracing = "0.7.0"
reqwest = { version = "0.13.3", features = ["json", "stream"] }
async-trait = "0.1.89"
octocrab = "0.54.0"
jsonwebtoken = "10.3.0"
base64 = "0.23.0"
rustls = "0.23.40"
chrono = "0.4.44"
regex = "1.12.3"
futures = "0.3.32"
semver = "1.0.28"
toml_edit = "0.25.11"
axum = { version = "0.8.9", features = ["tokio"] }
tempfile = "3.27.0"
flate2 = "1.1.9"
ipld-core = "0.4.3"
urlencoding = "2.1.3"
atrium-api = "0.25.8"
atrium-xrpc-client = "0.5.15"
git2 = { version = "0.21.0", features = ["vendored-openssl", "ssh"] }
clap = { version = "4.6.1", features = ["derive", "env"] }
ratatui = "0.30.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
hmac = "0.12.1"
sha2 = "0.10.9"
hex = "0.4.3"
